import './globals.css'
import { Roboto } from "next/font/google"
import { Work_Sans } from "next/font/google"

const roboto = Roboto({
  variable: "--font-roboto",
  subsets : ["latin"]
})

const work_sans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ['latin']
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <>
      <section className={`${roboto.variable} ${work_sans.variable}`}>
        {children}
      </section>
    </>
  )
}
